[package]
name = "reduct-macros"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"
authors = ["Alexey Timin <atimin@reduct.store>"]
description = "Macros crate for ReductStore"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.75", features = ["derive"] }
quote = "1.0.9"
